# Generated by Django 5.0.6 on 2024-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
