# Generated by Django 5.0.6 on 2024-07-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customerorder_customerorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='sales_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_preference',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
