# Generated by Django 5.0.6 on 2024-07-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customerorder_grand_total_customerorder_sales_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='delivery_time',
        ),
    ]
