# Generated by Django 5.0.6 on 2024-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_customerorder_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
