# Generated by Django 5.0.6 on 2024-07-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CustomerOrderItem',
        ),
    ]
