# Generated by Django 5.0.6 on 2024-08-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_anothermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherModel',
        ),
    ]
