# Generated by Django 5.0.7 on 2024-08-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_anothermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='new', max_length=10),
        ),
    ]
