# Generated by Django 5.0.7 on 2024-08-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_customerorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='popular_menu_images/')),
            ],
        ),
    ]
