from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('menu/', views.menu, name='menu'),
    path('menu/<str:category>/', views.menu, name='menu_category'),
    path('cart/', views.cart, name='cart'),
    path('manage_menu/', views.manage_menu, name='manage_menu'),
    path('edit_menu_item/<int:item_id>/', views.edit_menu_item, name='edit_menu_item'),
    path('delete_menu_item/<int:item_id>/', views.delete_menu_item, name='delete_menu_item'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('popular_menu/', views.popular_menu, name='popular_menu'),
    path('manage-popular-menu/', views.manage_popular_menu, name='manage_popular_menu'),
    path('delete-popular-menu-item/<int:item_id>/', views.delete_popular_menu_item, name='delete_popular_menu_item'),
    path('reviews/', views.review_list, name='review_list'),
    path('reviews/post/', views.post_review, name='post_review'),
    path('reserve/', views.reserve_table, name='reserve_table'),
    path('manager/', views.manager, name='manager'),
    path('staff/', views.staff, name='staff'),
    path('about_restaurant/', views.about_restaurant, name='about_restaurant'),
    path('location/', views.location, name='location'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin-login/', views.admin_login, name='admin_login'),  # Update to existing view
    path('custom-admin/', views.admin_page, name='custom_admin'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('manage-staff/', views.manage_staff, name='manage_staff'),
    path('manage-reservations/', views.manage_reservations, name='manage_reservations'),
    path('manage-orders/', views.manage_orders, name='manage_orders'),
    path('update-order-status/<int:order_id>/<str:status>/', views.update_order_status, name='update_order_status'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add-user/', views.add_user, name='add_user'),
    path('manage_reservations/', views.manage_reservations, name='manage_reservations'),
    path('reservation_success/', views.reservation_success, name='reservation_success'),
    path('edit_reservation/<int:reservation_id>/', views.edit_reservation, name='edit_reservation'),
    path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/', views.order, name='order'),
    path('order_placed/', views.order_placed, name='order_placed'),
    path('chatbot/', views.chatbot_view, name='chatbot'),
]
